### ISSUE TITLE
Kubernetes template

### ISSUE THREAD

**Issue by leseb** [ceph/cn#10]
To allow deployment in k8s.

**Comment by tmysl** [comment]
just out of curiosity how do you plan on deploying this for kube? via helm template? I was playing with this a little yesterday and ended up building out an service and sts as follows: 

```yaml 
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-nano
  namespace: ceph
  labels:
    app: ceph
    daemon: demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  type: ClusterIP
  selector:
    app: ceph
    daemon: demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ceph
    daemon: demo
  name: ceph-nano
  namespace: ceph
spec:
  replicas: 1
  serviceName: ceph-nano
  selector:
    matchLabels:
      app: ceph
  template:
    metadata:
      name: ceph-nano
      labels:
        app: ceph
        daemon: demo
    spec:
      containers:
      - image: ceph/daemon
        imagePullPolicy: Always
        name: ceph-nano
        ports:
        - containerPort: 8000
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2G
          requests:
            cpu: "2"
            memory: 2G
        env:
        - name: NETWORK_AUTO_DETECT
          value: "0"
        - name: CEPH_PUBLIC_NETWORK
          value: 10.118.0.0/16
        - name: MON_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RGW_CIVETWEB_PORT
          value: "8000"
        - name: CEPH_VERSION
          value: "luminous"
        - name: CEPH_DEMO_UID
          value: "nano"
        - name: CEPH_DAEMON
          value: "demo"
        - name: DEBUG
          value: "verbose"
        volumeMounts:
        - name: ceph-nano-pvc
          mountPath: /tmp
          subPath: osd-data
        - name: ceph-nano-pvc
          mountPath: /var/lib/ceph
          subPath: ceph-vars
        - name: ceph-nano-pvc
          mountPath: /etc/ceph
          subPath: ceph-conf
        - name: ceph-nano-pvc
          mountPath: /etc/ganesha
          subPath: ceph-ganesha
  volumeClaimTemplates:
  - metadata:
      name: ceph-nano-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100G
      storageClassName: rbd
```
Ironically enough we are using a ceph storage class to provsion storage =]
Main issue that i ran into is that if i don't provide stateful storage for `/etc/ceph/` and `/var/lib/ceph` i cant get the container to behave correctly. Also if the pod is deleted the ip changes, and the container fails to recover from this. the only way to handle this is to delete and recreate the stateful set/pv.
